services:
  stocks_db:
    image: postgres:16
    ports:
      - "55432:5432"
    environment:
      POSTGRES_DB: stocks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  stocks_web:
    build: .
    image: igorkoishman/stocks-app:latest
    ports:
      - "5050:5000"
    env_file: .env.docker
    volumes:
      - ${DATA_PATH}:/data
    depends_on:
      stocks_db:
        condition: service_healthy

volumes:
  pgdata: