services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: stocks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "55432:5432"
    volumes:
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: igorkoishman/stocks-app:latest
    ports:
      - "5050:5000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: stocks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    volumes:
      - ~/Downloads/Raw_Data:/data
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  pgdata: