services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: stocks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "80:5000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: stocks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    volumes:
      - /Users/ikoishman/Downloads/Raw_Data:/data
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: