name: Build, Tag, and Push Multi-Service Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-tag-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # for pushing tags
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Use PR labels for version bump (uses PR label 'major'/'minor' or defaults to 'patch')
      - name: Get PR for Commit
        id: pr
        uses: juliangruber/find-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.sha }}

      - name: Determine version bump
        id: bump
        run: |
          LABELS="${{ steps.pr.outputs.labels }}"
          if [[ "$LABELS" == *"major"* ]]; then
            echo "BUMP=major" >> $GITHUB_ENV
          elif [[ "$LABELS" == *"minor"* ]]; then
            echo "BUMP=minor" >> $GITHUB_ENV
          else
            echo "BUMP=patch" >> $GITHUB_ENV
          fi

      # Tag with next semver using PR label bump
      - name: GitHub Tag Action
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "v"
          release_branches: "main"
          default_bump: ${{ env.BUMP }}

      # Docker login (same as your working keys!)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & push app image (from ./docker/Dockerfile, context ./app)
      - name: Build and push app image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./docker/Dockerfile
          push: true
          tags: |
            igorkoishman/stocks-app:${{ steps.tag.outputs.new_tag }}
            igorkoishman/stocks-app:latest
